#!/bin/bash

# branch can be selected through $1
# project can be seleced through $2
# if no branch or project is specified, will prompt for selection

PS4="### "

repositories="
platform/system/bt
platform/hardware/libhardware
platform/packages/apps/Bluetooth
platform/frameworks/base
platform/external/bluetooth/bluedroid
kernel/common
device/sprd
device/sprd/scx35l
device/sprd/whale
device/sprd/whale2
vendor/sprd/modules/bt
vendor/sprd/proprietories-source/connconfig
vendor/sprd/proprietories-source/bt
vendor/sprd/open-source
vendor/sprd/wcn
vendor/sprd/proprietories-source/engmode
"

branches="
sprdroid6.0_ga1
sprdroid6.0_prime
sprdroid6.0_trunk
sprdroid6.0_trunk_k318_dev
sprdroid6.0_whale_dev
sprdroid_own_copyright_marshmallow
sprdroid_own_copyright_lollipop
sprdroid5.1_trunk
sprdroid5.1_prime
sprdroid5.1_prime_sharkls_15c_mp
sprdroid5.1_sharkl_15c_mp
sprdroid5.1_trunk
sprdroid5.1_trunk_bt_dev
sprdroid5.1_tshark_15a
sprdroid6.0_trunk_marlin2_Dev
sprdroid5.1_trunk_pike_full_dev
sprdroid6.0mr1_prime
"

if [ -z $2 ]
then
PS3='select repositories ' # Sets the prompt string.
                                       # Otherwise it defaults to #? .
select repository in $repositories
do
  break  # What happens if there is no 'break' here?
done
else
repository="$2"
fi

echo '###' repository selected: $repository '###'

if [ -z $1 ]
then

PS3='select branches ' # Sets the prompt string.
                                       # Otherwise it defaults to #? .
select branch in $branches
do
  break  # What happens if there is no 'break' here?
done
else
branch="$1"
fi

echo '###' branch selected: $branch '###'

set -x
# git clone gitadmin@gitsrv01.spreadtrum.com:android/platform/system/bt -b sprdroid6.0_ga1
git clone gitadmin@gitsrv01.spreadtrum.com:android/$repository -b $branch

